Update github-act_docker_login.yml

diff --git a/.github/workflows/github-act_docker_login.yml b/.github/workflows/github-act_docker_login.yml
--- a/.github/workflows/github-act_docker_login.yml
+++ b/.github/workflows/github-act_docker_login.yml
@@ -22,13 +22,15 @@ jobs:
         if: ${{ env.docker_credential_username == '' }}
         run: |
           echo 'check_ok=false' >> $GITHUB_ENV;
-          echo '::error title=Error::Require and Has NOT Set:`docker_credential_username`';
+          echo '::error title=Error::Require and Has NOT Set:`docker_credential_username` on vars';
+          exit 1
 
       - name: env.docker_credential_password
         if: ${{ env.docker_credential_password == '' }}
         run: |
           echo 'check_ok=false' >> $GITHUB_ENV;
-          echo '::error title=Error::Require and Has NOT Set:`docker_credential_password`';
+          echo '::error title=Error::Require and Has NOT Set:`docker_credential_password` on secrets';
+          exit 1
 
       - name: check ok?
         if: ${{ ! env.check_ok }}
